version: '3.1'

services:
# Continuous integration
  jenkins:
    image: jenkins:2.32.3-alpine
    ports:
      - "8080:8080"
    volumes:
      - /amf/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - amf

# Code quality
  sonarqube:
    image: sonarqube:6.3-alpine
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube
    volumes:
      - /amf/sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - /amf/sonarqube/sonarqube_data:/opt/sonarqube/data
      - /amf/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - /amf/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - postgres
    networks:
      - amf

# Database for Sonarqube
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
    volumes:
      - /amf/sonarqube/postgresql:/var/lib/postgresql
      - /amf/sonarqube/postgresql_data:/var/lib/postgresql/data
    networks:
      - amf

# Artifact storage
  nexus:
    image: sonatype/nexus3:3.2.1
    ports:
      - "8081:8081"
    networks:
      - amf

# Object storage
  minio:
    image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    environment:
      - MINIO_ACCESS_KEY=B3ON3UQ857SRQXA4642G
      - MINIO_SECRET_KEY=rdh+tfteSlsCRu7Rd00FgHVcnifILbZam1KYY3TG
    ports:
      - "8001:9000"
#    deploy:
#      mode: global
    command: server /export
    volumes:
      - minio:/export
    networks:
      - amf
      - minio

# Administation
  portainer:
    image: portainer/portainer:1.12.1
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: -H unix:///var/run/docker.sock
    ports:
      - "8002:9000"
    networks:
      - amf

networks:
  amf:
    driver: overlay
  minio:
    driver: overlay

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  minio:
  jenkins_home:
    driver: minio/minfs
    driver_opts:
      endpoint: http://minio:8001
      access-key: B3ON3UQ857SRQXA4642G
      secret-key: rdh+tfteSlsCRu7Rd00FgHVcnifILbZam1KYY3TG
      bucket: jenkins.home